#!/usr/bin/env bash
# This script displays information about subdomains of a domain

function info_subdomain {
	local domain=$1
	local subdomain=$2
	
	# if the subdomain($2) is not passed, display information for all subdomain of the domain passed
	if [ -z "$subdomain" ]; then
		subdomain=("wwww" "lb-01" "web-01" "web-02")
	else
		subdomain=("$subdomain")
	fi

	# iterate all element of the subdomain array
	for sub_dom in "${subdomain[@]}"; do
		# use awk to match line containing 'ANSWER SECTION'
		record_type=$(dig "$sub_dom.$domain" | awk '/ANSWER SECTION/ { getline; print $4 }')
		destination=$(dig "$sub_dom.$domain" | awk '/ANSWER SECTION/ { getline; print $5 }')
	echo "The subdomain $sub_dom is a $record_type record and points to $destination"
	done
	
}
info_subdomain "$1" "$2"
