#!/usr/bin/env bash
# Installs and configures an Nginx web server

# Check if Nginx is already installed
if dpkg -l | grep -q "nginx"; then
    echo "Nginx is already installed."
else
    # Update package lists and install Nginx
    if ! sudo apt-get update; then
        echo "Failed to update package lists. Exiting."
        exit 1
    fi

    if ! sudo apt-get -y install nginx; then
        echo "Failed to install Nginx. Exiting."
        exit 1
    fi
fi

# Allow Nginx HTTP traffic in the firewall
if ! sudo ufw allow "Nginx HTTP"; then
    echo "Failed to allow Nginx HTTP traffic in the firewall."
fi
# make a backup of the default config gile
if [ ! -e /etc/nginx/sites-available/default.bak ]; then
	cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
fi
# Create a simple index file in the default web root directory
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Start the Nginx service
if ! sudo service nginx start; then
	echo "Failed to start Nginx. Exiting."
	    exit 1
fi
echo "Installation and configuration successfull"
