#!/usr/bin/env bash
# Installs and configures an Nginx web server
# configure nginx to redirect /redirect_me to another page

if dpkg -l | grep -q "nginx"; then
    echo "Nginx is already installed."
else
    if ! sudo apt-get update; then
        echo "Failed to update package lists. Exiting."
        exit 1
    fi

    if ! sudo apt-get -y install nginx; then
        echo "Failed to install Nginx. Exiting."
        exit 1
    fi
fi

if ! sudo ufw allow "Nginx HTTP"; then
    echo "Failed to allow Nginx HTTP traffic in the firewall."
fi


echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

if [ ! -e /etc/nginx/sites-available/default.bak ]; then
	cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
fi

redirect_to="https://github.com/chimaskyy"

# Update the Nginx configuration to perform a redirect
sudo tee -a /etc/nginx/sites-available/default > /dev/null << EOF
server {
	listen 80;
	listen [::]:80;
	
	server_name techinit.tech www.techinit.com;
	root /var/www/html;
	index index.html index.htm;
	
	location /redirect_me {
	     return 301 $redirect_to;
	}
}
EOF

sudo service nginx restart
