#!/usr/bin/env bash
# Installs and configures an Nginx web server
# configure nginx to redirect /redirect_me to another page

if dpkg -l | grep -q "nginx"; then
    echo "Nginx is already installed."
else
    if ! sudo apt-get update; then
	echo "Failed to update package lists. Exiting."
	exit 1
    fi

    if ! sudo apt-get -y install nginx; then
        echo "Failed to install Nginx. Exiting."
	exit 1
    fi
fi

if ! sudo ufw allow "Nginx HTTP"; then
    echo "Failed to allow Nginx HTTP traffic in the firewall."
fi

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

if [ -e /etc/nginx/sites-available/default ]; then
	    # Backup existing configuration
    if ! sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak; then
	 echo "Failed to backup the Nginx configuration. Continuing without backup."
    else 
	 echo "Nginx configuration backed up successfully."
    fi

fi

sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://github.com/chimaskyy permanent; ' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

replace="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$replace/" /etc/nginx/sites-available/default

sudo service nginx restart

echo "Nginx configured successfully."
