#!/usr/bin/env bash

# This script install and configure HAProxy on lb-01 server
# Configures HAProxy to send traffic to web-01 and web-02 servers
# ROundrobin algorithm is used to distribute request
# Ensure that HAProxy can be managed via an init script


CONFIG_FILE="/etc/haproxy/haproxy.cfg"

# backup config file
sudo cp "$CONFIG_FILE" "CONFIG_FILE.bak"

# update and install HAProxy
sudo apt-get -y update
sudo apt-get install -y haproxy

# Configure HAproxy so that it send traffic to web-01 and web-02
sudo tee "$CONFIG_FILE" > /dev/null <<EOF
frontend front
    bind *:80
    default_backend back

backend back
    balance roundrobin
    server web1 54.175.8.50:80 check
    server web2 54.237.39.190:80 check
EOF

if sudo service haproxy restart; then
	echo "Configuratuin succesful"
else
	echo "Error restarting"
fi
