#!/usr/bin/env bash
# This script checks if nginx is installed and restart it, if not install and restart it

# check is nginx is installed
if dpkg -l | grep -q nginx; then
	echo "nginx is installed"
	sudo service nginx restart
	exit 0
fi

# update apt packages
sudo apt-get update

# install nginx
if sudo apt-get install -y nginx; then
	echo "nginx succesfully installed"
	sudo service nginx restart
else
	echo "nginx installation failed"
fi
