#!/usr/bin/env bash
# test signals

pid=$$

pid_file="/var/run/myscript.pid"

echo $pid > $pid_file

function sigterm()
{
	echo "I hate the kill command"
	rm /var/run/myscript.pid
	exit
}
function sigint()
{
	echo "Y U no love me?!"
	exit
}

while true
do
	echo "To infinity and beyond"
	
	sleep 2

	trap sigterm SIGTERM
	trap sigint SIGINT
	trap exit SIGQUIT
done
