#!/usr/bin/env bash
# displays "To infinity and beyond" indefinitely
#+ with a sleep 2 in between each iteration
#+ "I am invincible!!!" when receiving a SIGTERM signal

function sigterm ()
{
	echo "I am invincible!!!"
}

while true
do
	echo "To infinity and beyond"
	sleep 2

	trap sigterm SIGTERM
done

