#!/usr/bin/env bash
# This bash script displays number 1 to 100

count=1

while [ $count -le 100 ]
do
	if [ $((count % 3)) -eq 0 ] && [ $((count % 5)) -ne 0 ]
	then
		echo "Fizz"

	elif [ $((count % 5)) -eq 0 ] && [ $((count % 3)) -ne 0 ]
	then
		echo "Buzz"
	
	elif [ $((count % 3)) -eq 0 ] && [ $((count % 5)) -eq 0 ]
	then
		echo "FizzBuzz"
	else
		echo $count
	fi
	((count++))
done

