#!/usr/bin/env bash
# This bash script displays loops from 1 t0 20
#+ displays "bad luck" for the 4th iteration
#+ displays "good luck" for the 8th iteration
#+ displays "Best School" for other iteration

count=1

while [ $count -le 10 ]
do
        if [ $count = 4 ]
        then
                echo "bad luck"
        elif [ $count = 8 ]
	then
                echo "good luck"
	else
		echo "Best School"
        fi

        ((count++))

done

