#!/usr/bin/env bash
# This bash script displays the time for 12 hours and 59 minutes
# display hours from 0 to 12
# display minutes from 1 to 59

hour=0
minute=1

while [ $hour -lt 13 ]
do
	echo "Hour: $hour"

	while [ $minute -lt 60 ]
	do
		#echo "hour: $hour"
		echo $minute
		((minute++))
	done
	((hour++))
	minute=1
	
done

