#!/usr/bin/env bash
# This bash script gives information abouth the 'school' file

f_name=school

if [ -e $f_name ]
then
	echo "school file exists"

	if [ -s $f_name ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	
	if [ -f $f_name ]
	then
		echo "school is a regular file"
	else
		echo ""
	fi
else
	echo "school file does not exist"
fi

