#!/usr/bin/env bash
# This bash script gives information abouth the 'school' file

f_name=school

if [ -e $f_name ]
then
	echo "$f_name file exists"

	if [ -s $f_name ]
	then
		echo "$f_name file is not empty"
	else
		echo "$f_name file is empty"
	fi
	
	if [ -f $f_name ]
	then
		echo "school is a regular file"
	fi
else
	echo "$f_name file does not exist"
	exit
fi

