#!/usr/bin/env bash
#  Configures an Ubuntu server 
# changes facebook and localhost IPv4 to different IP

echo "127.0.0.2     localhost" > ~/hosts_new
echo "8.8.8.8     facebook.com" >> ~/hosts_new

tail -n +2 /etc/hosts >> ~/hosts_new
cp -f ~/hosts_new /etc/hosts
